# Generated by Django 4.0.2 on 2022-02-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_librarian',
            field=models.BooleanField(default=False),
        ),
    ]
