# Generated by Django 4.0.2 on 2022-02-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>', max_length=50),
        ),
    ]
