# Generated by Django 4.0.2 on 2022-02-21 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
